# Allows only loadgenerator pods to access frontend service.
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-loadgen-to-frontend
  annotations:
    tier:: application
spec:
  selector: app == 'loadgenerator'
  egress:
    - action: Allow
      protocol: TCP
      destination:
        selector: app == 'frontend'
        ports: [8080]
  types:
    - Egress